### ISSUE TITLE
Jan 2019 Poster Review Request

### ISSUE THREAD

**Issue by achubbz** [arfc/i2cner#69]
@katyhuff could you please review the poster, which is here: https://github.com/arfc/i2cner/tree/master/doc/2019-01-poster? Thank you.

**Comment by katyhuff** [comment]
This is how it builds for me. Looks good. 

[poster.pdf](https://github.com/arfc/i2cner/files/2734863/poster.pdf)


- consider a more concise way to explain the scenarios (rather than "i2cner technologies disabled", perhaps "no i2cner technologies") and consider different bolding? Or, merely a table with checkboxes? (rows are scenario numbers, columns are "conventional", "i2cner", and "new nuclear")
- a close parenthesis is necessary when referencing Figs 1&2)
- perhaps the legend for all four plots does not need to be repeated, and space could be saved with rearrangement. 

I still have some questions about the results, as many viewers will. Looking forward to chatting about them more this week!

**Comment by achubbz** [comment]
Thanks, I've made some changes.
I'm not sure about the last one since the legend changes a bit from plot to plot.

**Comment by katyhuff** [comment]
It would be good if you can make a legend that is a superset of all plots (hopefully no single color is used to mean two different things in the set of plots). I think it would save some helpful space.

**Comment by achubbz** [comment]
Separated legend in the second draft, which is here: https://github.com/arfc/i2cner/tree/master/doc/2019-01-poster/draft2-legend

**Comment by achubbz** [comment]
@katyhuff Final draft. I fixed as many bugs as I could, added some text.
[poster.pdf](https://github.com/arfc/i2cner/files/2752505/poster.pdf)

**Comment by achubbz** [comment]
Thank you. I've reduced the text as much as I could have. I hope this better.
[poster.pdf](https://github.com/arfc/i2cner/files/2752780/poster.pdf)

**Comment by achubbz** [comment]
Thanks! I'll email this to Sandra later today.
